### ISSUE TITLE
Bug fix in Assignment_6 in DBMSL

### ISSUE THREAD

**Issue by swarajgosavi** [shubham0204/PICT_Coursework#1]
Syntax error in line 8 of Assignment_6 in dbmsl branch

`declare cursor c1 for select eid from old_employees where eid > employee_id;`

Should be

`declare c1 cursor for select eid from old_employees where eid > employee_id;`

The Syntax is 
DECLARE CURSOR_Name CURSOR FOR SELECT SELECT_Statement

**Comment by shubham0204** [comment]
Fixed @swarajgosavi. The changes will soon reflect in the code.
Thanks for improving the code!
